---
- name: Install nginx
  sudo: yes
  apt: pkg=nginx-full
  tags: nginx

- name: Setup nginx.conf
  sudo: yes
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  tags: nginx

- name: Setup reverse proxy
  sudo: yes
  template: src=default dest=/etc/nginx/sites-available/
  tags: nginx

- name: Start nginx
  sudo: yes
  service: name=nginx state=restarted
  tags: nginx

- name: Add upstart script
  sudo: yes
  template: src=upstart.conf dest=/etc/init/nginx.conf
  tags: nginx

